-- Canonical schema orchestrator.
-- Applies deterministic, deduplicated SQL modules from migrations/.

\ir ../../../migrations/00_extensions.sql
\ir ../../../migrations/10_books.sql
\ir ../../../migrations/11_book_external_ids.sql
\ir ../../../migrations/12_authors.sql
\ir ../../../migrations/13_author_external_ids.sql
\ir ../../../migrations/14_book_authors_join.sql
\ir ../../../migrations/15_work_clusters.sql
\ir ../../../migrations/16_work_cluster_members.sql
\ir ../../../migrations/17_book_work_editions_view.sql
\ir ../../../migrations/18_book_tags.sql
\ir ../../../migrations/19_book_tag_equivalents.sql
\ir ../../../migrations/20_book_tag_assignments.sql
\ir ../../../migrations/21_book_raw_data.sql
\ir ../../../migrations/22_book_dimensions.sql
\ir ../../../migrations/23_book_image_links.sql
\ir ../../../migrations/24_book_collections.sql
\ir ../../../migrations/25_book_collections_join.sql
\ir ../../../migrations/26_book_search_view.sql
\ir ../../../migrations/27_search_functions.sql
\ir ../../../migrations/28_slug_functions.sql
\ir ../../../migrations/29_book_recommendations.sql
\ir ../../../migrations/30_events_outbox.sql
\ir ../../../migrations/31_book_slug_redirect.sql
\ir ../../../migrations/32_author_normalization_functions.sql
\ir ../../../migrations/33_slug_migration_helpers.sql
\ir ../../../migrations/34_work_clustering_isbn_functions.sql
\ir ../../../migrations/35_work_clustering_google_single_function.sql
\ir ../../../migrations/36_work_clustering_primary_trigger_and_editions.sql
\ir ../../../migrations/37_work_clustering_google_batch_and_stats.sql
\ir ../../../migrations/38_work_clustering_data_hygiene.sql
\ir ../../../migrations/39_title_author_clustering_functions.sql
\ir ../../../migrations/40_book_ai_content.sql
\ir ../../../migrations/41_book_ai_content_nullable_reader_fit.sql
\ir ../../../migrations/42_book_image_links_grayscale.sql
\ir ../../../migrations/43_cover_image_priority_function.sql
\ir ../../../migrations/44_recent_book_views.sql
\ir ../../../migrations/45_page_view_events.sql
\ir ../../../migrations/46_propagate_grayscale_to_siblings.sql
\ir ../../../migrations/47_book_seo_metadata.sql
