-- Books - canonical record
-- This is our single source of truth for book data, merged from all providers
create table if not exists books (
  id uuid primary key, -- UUIDv7 generated by our application (NOT provider IDs)
  title text not null, -- JSON: volumeInfo.title
  constraint books_title_non_blank_check check (btrim(title) <> ''),
  constraint books_title_leading_character_check check (
    regexp_replace(title, '^[[:space:]]+', '') ~ '^[[:alpha:][:digit:]]'
  ),
  subtitle text, -- JSON: volumeInfo.subtitle
  description text, -- JSON: volumeInfo.description (HTML from providers)
  isbn10 text, -- Canonical ISBN-10 (best available from all sources)
  isbn13 text, -- Canonical ISBN-13 (best available from all sources)
  published_date date, -- JSON: volumeInfo.publishedDate (parsed from various formats)
  language text, -- JSON: volumeInfo.language (ISO 639-1 code like 'en')
  publisher text, -- JSON: volumeInfo.publisher
  page_count integer, -- JSON: volumeInfo.pageCount or volumeInfo.printedPageCount
  -- Removed edition_number and edition_group_key (replaced with work_clusters system)
  -- Canonical cover stored in book_image_links; books table no longer carries cover path
  slug text unique, -- SEO-friendly URL slug (e.g., 'harry-potter-philosophers-stone-j-k-rowling')
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Generated search vector for full-text search
  search_vector tsvector generated always as (
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(subtitle, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(publisher, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'D')
  ) stored
);

create index if not exists idx_books_isbn13 on books(isbn13) where isbn13 is not null;
create index if not exists idx_books_isbn10 on books(isbn10) where isbn10 is not null;
create unique index if not exists uq_books_isbn13 on books(isbn13) where isbn13 is not null;
create unique index if not exists uq_books_isbn10 on books(isbn10) where isbn10 is not null;
-- Removed idx_books_edition_group_key index (using work_clusters instead)
create index if not exists idx_books_slug on books(slug); -- Always index slug for URL lookups
create index if not exists idx_books_created_at on books(created_at desc);
create index if not exists idx_books_updated_at on books(updated_at desc);
create index if not exists idx_books_search_vector on books using gin (search_vector);

-- Table and column comments for books
comment on table books is 'Canonical book records - single source of truth merged from all providers';
comment on column books.id is 'UUIDv7 generated by our application (NOT provider IDs)';
comment on column books.title is 'Book title from volumeInfo.title';
comment on column books.subtitle is 'Book subtitle from volumeInfo.subtitle';
comment on column books.description is 'Book description from volumeInfo.description (HTML from providers)';
comment on column books.isbn10 is 'Canonical ISBN-10 (best available from all sources)';
comment on column books.isbn13 is 'Canonical ISBN-13 (best available from all sources)';
comment on column books.published_date is 'Publication date from volumeInfo.publishedDate';
comment on column books.language is 'Language code (ISO 639-1) from volumeInfo.language';
comment on column books.publisher is 'Publisher name from volumeInfo.publisher';
comment on column books.page_count is 'Page count from volumeInfo.pageCount or printedPageCount';
-- Removed edition_number and edition_group_key column comments (using work_clusters instead)
comment on column books.slug is 'SEO-friendly URL slug generated once at creation, remains stable even if title/authors change';

-- ---------------------------------------------------------------------------
-- Legacy data cleanup consolidated into canonical books migration.
-- ---------------------------------------------------------------------------
-- Clean book rows with leading non-alphanumeric title prefixes and enforce title guard constraints.
-- Safe to run multiple times.

BEGIN;

ALTER TABLE books DROP CONSTRAINT IF EXISTS books_title_non_blank_check;
ALTER TABLE books DROP CONSTRAINT IF EXISTS books_title_leading_character_check;

WITH cleaned_titles AS (
  SELECT
    b.id,
    b.title AS original_title,
    btrim(regexp_replace(b.title, '^[[:space:]]*[^[:alpha:][:digit:]]+', '')) AS cleaned_title
  FROM books b
),
updated_titles AS (
  UPDATE books b
  SET
    title = cleaned.cleaned_title,
    updated_at = now()
  FROM cleaned_titles cleaned
  WHERE b.id = cleaned.id
    AND b.title IS DISTINCT FROM cleaned.cleaned_title
  RETURNING b.id
)
SELECT count(*) FROM updated_titles;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM books
    WHERE btrim(title) = ''
       OR regexp_replace(title, '^[[:space:]]+', '') ~ '^[^[:alpha:][:digit:]]'
  ) THEN
    RAISE EXCEPTION 'book title cleanup left rows that violate leading-character/non-blank requirements';
  END IF;
END
$$;

ALTER TABLE books
  ADD CONSTRAINT books_title_non_blank_check CHECK (btrim(title) <> '');

ALTER TABLE books
  ADD CONSTRAINT books_title_leading_character_check CHECK (
    regexp_replace(title, '^[[:space:]]+', '') ~ '^[[:alpha:][:digit:]]'
  );

COMMIT;
