-- Align book similarity storage with the section-fusion embedding contract.
--
-- This is an expand migration. The original `embedding` column remains for
-- compatibility while new writes populate `qwen_4b_fp16` plus auditable source
-- text/json/hash fields.

alter table book_similarity_vectors
  add column if not exists source_type text not null default 'book',
  add column if not exists source_text text,
  add column if not exists source_json jsonb,
  add column if not exists source_hash text,
  add column if not exists qwen_4b_fp16 halfvec(2560),
  add column if not exists computed_at timestamptz;

alter table book_similarity_vectors
  drop constraint if exists book_similarity_vectors_source_type_check,
  add constraint book_similarity_vectors_source_type_check check (source_type = 'book');

alter table book_similarity_vectors
  drop constraint if exists book_similarity_vectors_source_hash_check,
  add constraint book_similarity_vectors_source_hash_check
    check (source_hash is null or source_hash ~ '^[a-f0-9]{64}$');

update book_similarity_vectors
set qwen_4b_fp16 = coalesce(qwen_4b_fp16, embedding),
    computed_at = coalesce(computed_at, updated_at)
where qwen_4b_fp16 is null
   or computed_at is null;

-- Note: uniqueness on (book_id, model_version, profile_hash) is already enforced by
-- uq_book_similarity_vectors_current_profile from migration 50. Because source_type is
-- pinned to 'book' by the CHECK above, a four-column variant would be strictly redundant.

create index if not exists idx_book_similarity_vectors_source_hash
  on book_similarity_vectors (source_type, model_version, profile_hash, source_hash);

create index if not exists idx_book_similarity_vectors_computed
  on book_similarity_vectors (source_type, model_version, profile_hash, computed_at desc);

create index if not exists idx_book_similarity_vectors_qwen_hnsw
  on book_similarity_vectors using hnsw (qwen_4b_fp16 halfvec_cosine_ops)
  where qwen_4b_fp16 is not null;

comment on column book_similarity_vectors.source_type is
  'Source discriminator for the embedding row; currently always book.';
comment on column book_similarity_vectors.source_text is
  'Rendered section-fusion source text used for diagnostics and source-hash reproducibility.';
comment on column book_similarity_vectors.source_json is
  'Structured section-fusion metadata: profile, regime, model, section weights, and hashes.';
comment on column book_similarity_vectors.source_hash is
  'SHA-256 hash of the rendered source contract; refresh is required when it changes.';
comment on column book_similarity_vectors.qwen_4b_fp16 is
  'Searchable fused halfvec(2560) embedding generated by weighted section fusion.';
comment on column book_similarity_vectors.computed_at is
  'Timestamp when the fused embedding contract was last computed.';
