import "@testing-library/jest-dom/vitest";

(window as Window & { __FMB_ROUTE_MANIFEST__?: unknown }).__FMB_ROUTE_MANIFEST__ = {
  version: 1,
  publicRoutes: [
    {
      name: "home",
      matchType: "exact",
      pattern: "/",
      paramNames: [],
      defaults: {},
      allowedQueryParams: [],
      canonicalPathTemplate: "/",
    },
    {
      name: "search",
      matchType: "exact",
      pattern: "/search",
      paramNames: [],
      defaults: {},
      allowedQueryParams: ["query", "year", "page", "orderBy", "source", "coverSource", "resolution", "genre", "view"],
      canonicalPathTemplate: "/search",
    },
    {
      name: "explore",
      matchType: "exact",
      pattern: "/explore",
      paramNames: [],
      defaults: {},
      allowedQueryParams: ["query", "year", "page", "orderBy", "source", "coverSource", "resolution", "genre", "view"],
      canonicalPathTemplate: "/explore",
    },
    {
      name: "categories",
      matchType: "exact",
      pattern: "/categories",
      paramNames: [],
      defaults: {},
      allowedQueryParams: ["query", "year", "page", "orderBy", "source", "coverSource", "resolution", "genre", "view"],
      canonicalPathTemplate: "/categories",
    },
    {
      name: "book",
      matchType: "regex",
      pattern: "^/book/([^/]+)$",
      paramNames: ["identifier"],
      defaults: {},
      allowedQueryParams: ["query", "page", "orderBy", "view"],
      canonicalPathTemplate: "/book/{identifier}",
    },
    {
      name: "sitemap",
      matchType: "exact",
      pattern: "/sitemap",
      paramNames: [],
      defaults: { view: "authors", letter: "A", page: "1" },
      allowedQueryParams: ["view", "letter", "page"],
      canonicalPathTemplate: "/sitemap/authors/A/1",
    },
    {
      name: "sitemap",
      matchType: "regex",
      pattern: "^/sitemap/(authors|books)/([^/]+)/(\\d+)$",
      paramNames: ["view", "letter", "page"],
      defaults: {},
      allowedQueryParams: [],
      canonicalPathTemplate: "/sitemap/{view}/{letter}/{page}",
    },
    {
      name: "notFound",
      matchType: "exact",
      pattern: "/404",
      paramNames: [],
      defaults: {},
      allowedQueryParams: [],
      canonicalPathTemplate: "/404",
    },
  ],
  passthroughPrefixes: ["/api", "/admin", "/actuator", "/ws", "/topic", "/sitemap.xml", "/sitemap-xml", "/r"],
};
